"""
AuditLens PDF Report Exporter — with visual bar chart.

New in this version:
- T3-4: horizontal bar chart for severity distribution (drawn with fpdf2 rectangles)
- Compliance coverage section listing triggered OWASP categories
"""

from __future__ import annotations

import os
from collections import defaultdict
from datetime import datetime
from typing import Dict, List

from fpdf import FPDF

_COLORS: Dict[str, tuple] = {
    'CRITICAL': (220, 0, 0),
    'HIGH': (255, 102, 0),
    'MEDIUM': (204, 153, 0),
    'LOW': (0, 102, 204),
}

_CHART_MAX_WIDTH = 120  # mm — max bar width


class PdfExporter(FPDF):
    def __init__(self):
        super().__init__()
        self.findings: List[dict] = []
        self.stats: Dict[str, int] = {'CRITICAL': 0, 'HIGH': 0, 'MEDIUM': 0, 'LOW': 0}
        self.set_auto_page_break(auto=True, margin=15)
        # DejaVu Unicode fonts (built into fpdf2 ≥ 2.7)
        self.add_font('DejaVu', '', 'DejaVuSansCondensed.ttf', uni=True)
        self.add_font('DejaVu', 'B', 'DejaVuSansCondensed-Bold.ttf', uni=True)

    def add_finding(self, finding: dict):
        self.findings.append(finding)
        sev = finding.get('severity', 'LOW').upper()
        if sev in self.stats:
            self.stats[sev] += 1

    def header(self):
        self.set_font('DejaVu', 'B', 14)
        self.cell(0, 10, 'AuditLens — Security Audit Report', border=0,
                  new_x='LMARGIN', new_y='NEXT', align='C')
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font('DejaVu', '', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} — Generated by AuditLens', border=0, align='C')
        self.set_text_color(0, 0, 0)

    # ── Bar chart ─────────────────────────────────────────────────────────────
    def _draw_bar_chart(self):
        total = max(sum(self.stats.values()), 1)
        self.set_font('DejaVu', 'B', 11)
        self.cell(0, 8, 'Severity Distribution', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)

        for sev in ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'):
            count = self.stats[sev]
            bar_w = int((count / total) * _CHART_MAX_WIDTH)
            color = _COLORS[sev]

            # Label
            self.set_font('DejaVu', '', 10)
            self.set_text_color(*color)
            self.cell(22, 7, sev, border=0)
            self.set_text_color(0, 0, 0)

            # Bar (filled rectangle)
            x = self.get_x()
            y = self.get_y() + 1
            if bar_w > 0:
                self.set_fill_color(*color)
                self.rect(x, y, bar_w, 5, style='F')

            # Count label after bar
            self.set_xy(x + _CHART_MAX_WIDTH + 3, self.get_y())
            self.cell(15, 7, str(count), border=0, new_x='LMARGIN', new_y='NEXT')
            self.ln(1)

        self.set_fill_color(255, 255, 255)
        self.ln(5)

    # ── Compliance coverage ───────────────────────────────────────────────────
    def _draw_compliance_section(self):
        from collections import Counter
        compliance_counts: Counter = Counter()
        for f in self.findings:
            for tag in f.get('compliance', []):
                compliance_counts[tag] += 1

        if not compliance_counts:
            return

        self.set_font('DejaVu', 'B', 11)
        self.cell(0, 8, 'Compliance Coverage', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)

        self.set_font('DejaVu', '', 9)
        self.set_fill_color(245, 245, 245)
        self.cell(80, 7, 'Framework / Standard', border=1, align='C', fill=True)
        self.cell(30, 7, 'Findings', border=1, new_x='LMARGIN', new_y='NEXT', align='C', fill=True)

        self.set_fill_color(255, 255, 255)
        for tag, count in sorted(compliance_counts.items(), key=lambda x: -x[1]):
            self.cell(80, 6, str(tag), border=1)
            self.cell(30, 6, str(count), border=1, new_x='LMARGIN', new_y='NEXT', align='C')

        self.ln(8)

    # ── Main report ───────────────────────────────────────────────────────────
    def generate_report(self, output_path: str = 'audit_report.pdf'):
        self.add_page()

        # Header meta
        self.set_font('DejaVu', '', 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} UTC',
                  border=0, new_x='LMARGIN', new_y='NEXT', align='R')
        self.set_text_color(0, 0, 0)
        self.ln(4)

        # ── 1. Executive Summary ──────────────────────────────────────────────
        self.set_font('DejaVu', 'B', 13)
        self.cell(0, 9, '1. Executive Summary', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)

        self.set_font('DejaVu', '', 11)
        total = sum(self.stats.values())
        self.cell(0, 7, f'Total Findings: {total}', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(4)

        # Severity table
        self.set_fill_color(240, 240, 240)
        self.set_font('DejaVu', 'B', 10)
        self.cell(50, 8, 'Severity', border=1, align='C', fill=True)
        self.cell(35, 8, 'Count', border=1, new_x='LMARGIN', new_y='NEXT', align='C', fill=True)

        self.set_font('DejaVu', '', 10)
        for sev in ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'):
            self.set_text_color(*_COLORS[sev])
            self.cell(50, 7, sev, border=1, align='C')
            self.set_text_color(0, 0, 0)
            self.cell(35, 7, str(self.stats[sev]), border=1,
                      new_x='LMARGIN', new_y='NEXT', align='C')

        self.ln(8)

        # ── 2. Bar chart ──────────────────────────────────────────────────────
        self.set_font('DejaVu', 'B', 13)
        self.cell(0, 9, '2. Risk Overview', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)
        self._draw_bar_chart()

        # ── 3. Compliance coverage ────────────────────────────────────────────
        self.set_font('DejaVu', 'B', 13)
        self.cell(0, 9, '3. Compliance Coverage', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(2)
        self._draw_compliance_section()

        # ── 4. Finding details ────────────────────────────────────────────────
        self.set_font('DejaVu', 'B', 13)
        self.cell(0, 9, '4. Finding Details', border=0, new_x='LMARGIN', new_y='NEXT')
        self.ln(3)

        if not self.findings:
            self.set_font('DejaVu', '', 11)
            self.set_text_color(0, 153, 0)
            self.cell(0, 8, 'No vulnerabilities found.', border=0, new_x='LMARGIN', new_y='NEXT')
            self.set_text_color(0, 0, 0)
        else:
            for idx, f in enumerate(self.findings, 1):
                sev = f.get('severity', 'LOW').upper()
                self.set_text_color(*_COLORS.get(sev, (0, 0, 0)))
                self.set_font('DejaVu', 'B', 11)
                self.multi_cell(0, 7, f"#{idx} [{sev}] {f.get('name', '')}", border=0)
                self.set_text_color(0, 0, 0)
                self.set_font('DejaVu', '', 9)
                self.multi_cell(0, 5, f"Rule:     {f.get('rule_id', '')}", border=0)
                self.multi_cell(
                    0, 5,
                    f"Location: {f.get('file', '')} (line {f.get('line', '')})",
                    border=0,
                )
                self.multi_cell(0, 5, f"Details:  {f.get('description', '')}", border=0)
                if f.get('compliance'):
                    self.multi_cell(0, 5, f"Compliance: {', '.join(f['compliance'])}", border=0)
                self.ln(2)
                self.line(self.get_x(), self.get_y(), self.get_x() + 180, self.get_y())
                self.ln(4)

        self.output(output_path)
        print(
            f'\n\033[92m[AuditLens]\033[0m PDF saved: '
            f'\033[1m{os.path.abspath(output_path)}\033[0m'
        )
