"""
AuditLens Remediation Engine — Automated fix generation, validation, and deployment.

Features:
- AI-powered fix generation for security findings
- Pre-merge safety validation (tests + re-scan)
- GitHub/GitLab/Bitbucket PR automation
- Rollback on failure with snapshot management
- Batch processing with parallel execution
- Comprehensive fix history tracking

Usage:
    from auditlens.remediation_engine import RemediationEngine, RemediationConfig

    config = RemediationConfig(
        vcs_type=VCSType.GITHUB,
        repo='owner/repo',
        base_branch='main',
        auto_merge=False,
        require_review=True,
    )
    engine = RemediationEngine(config, api_key=os.environ['ANTHROPIC_API_KEY'])

    findings = [...]  # from analyzer.run_static_analysis()
    report = engine.remediate(findings, mode=RemediationMode.SAFE)
    print(f"Success rate: {report.success_rate:.1%}")
"""

from __future__ import annotations

import enum
import hashlib
import json
import logging
import os
import re
import sqlite3
import subprocess
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import requests

# ── Enums ─────────────────────────────────────────────────────────────────────

class VCSType(enum.Enum):
    """Version Control System types."""
    GITHUB = 'github'
    GITLAB = 'gitlab'
    BITBUCKET = 'bitbucket'


class RemediationMode(enum.Enum):
    """Remediation execution modes."""
    SAFE = 'safe'           # Only fix HIGH/CRITICAL with high confidence
    MODERATE = 'moderate'   # Fix MEDIUM+ with moderate confidence
    AGGRESSIVE = 'aggressive'  # Fix all findings, lower confidence threshold


class FixStrategy(enum.Enum):
    """Alias for RemediationMode for batch operations."""
    SAFE = RemediationMode.SAFE
    MODERATE = RemediationMode.MODERATE
    AGGRESSIVE = RemediationMode.AGGRESSIVE


class PRStatus(enum.Enum):
    """Pull Request status."""
    OPEN = 'open'
    MERGED = 'merged'
    CLOSED = 'closed'
    FAILED = 'failed'


class FixStatus(enum.Enum):
    """Fix application status."""
    SUCCESS = 'success'
    FAILED = 'failed'
    ROLLED_BACK = 'rolled_back'


class RiskLevel(enum.Enum):
    """Risk level for proposed fixes."""
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'


# ── Data Structures ───────────────────────────────────────────────────────────

@dataclass
class RemediationConfig:
    """Configuration for remediation engine."""
    vcs_type: VCSType
    repo: str  # Format: 'owner/repo'
    base_branch: str = 'main'
    auto_merge: bool = False
    require_review: bool = True
    max_fixes_per_run: int = 10
    rollback_on_test_failure: bool = True
    snapshot_retention_days: int = 30
    vcs_token: Optional[str] = None
    vcs_url: Optional[str] = None  # For self-hosted GitLab/Bitbucket


@dataclass
class FixProposal:
    """Proposed fix generated by AI."""
    finding: dict
    diff: str
    explanation: str
    confidence_score: float
    affected_files: List[str]
    estimated_risk: RiskLevel
    generation_time_ms: int = 0


@dataclass
class ValidationResult:
    """Result of fix validation."""
    passed: bool
    tests_run: int
    tests_failed: int
    new_findings: List[dict]
    original_finding_resolved: bool
    execution_time_ms: int
    error_message: Optional[str] = None


@dataclass
class PRMetadata:
    """Pull Request metadata."""
    pr_id: str
    pr_url: str
    branch: str
    commit_sha: str
    created_at: datetime
    status: PRStatus
    finding_id: str


@dataclass
class PRResult:
    """Result of PR creation."""
    pr_metadata: Optional[PRMetadata]
    success: bool
    error_message: Optional[str] = None


@dataclass
class BatchResult:
    """Result of batch fix operation."""
    total_attempted: int
    successful: int
    failed: int
    pr_urls: List[str]
    errors: List[Tuple[str, str]]  # (finding_id, error_message)


@dataclass
class RollbackResult:
    """Result of rollback operation."""
    success: bool
    reverted_files: List[str]
    error_message: Optional[str] = None


@dataclass
class ScheduleResult:
    """Result of scheduling remediation."""
    schedule_id: str
    cron_expression: str
    findings_count: int
    approval_required: bool
    created_at: datetime


@dataclass
class RemediationReport:
    """Final report of remediation session."""
    total_findings: int
    fixes_attempted: int
    fixes_successful: int
    fixes_failed: int
    prs_created: List[PRMetadata]
    rollbacks: int
    execution_time_seconds: float
    success_rate: float


@dataclass
class SnapshotID:
    """Unique identifier for a snapshot."""
    id: str
    timestamp: datetime


@dataclass
class Snapshot:
    """File state snapshot for rollback."""
    snapshot_id: SnapshotID
    finding_key: str
    file_states: Dict[str, str]  # file_path -> content_hash
    git_stash_ref: Optional[str] = None


@dataclass
class FixRecord:
    """Persistent fix record for SQLite."""
    id: Optional[int] = None
    finding_key: str = ''
    pr_metadata: str = ''  # JSON
    applied_at: Optional[datetime] = None
    status: FixStatus = FixStatus.SUCCESS
    validation_result: str = ''  # JSON
    rollback_reason: Optional[str] = None


@dataclass
class TestSuite:
    """Detected test suite configuration."""
    runner: str  # pytest, jest, go test, etc.
    test_dir: str
    command: List[str]
    timeout: int = 300


@dataclass
class TestResult:
    """Test execution result."""
    passed: bool
    tests_run: int
    tests_failed: int
    execution_time_ms: int
    stdout: str
    stderr: str


@dataclass
class TestMetrics:
    """Parsed test metrics."""
    total: int
    passed: int
    failed: int
    skipped: int = 0


# ── Logger Setup ──────────────────────────────────────────────────────────────

logger = logging.getLogger('auditlens.remediation')
logger.setLevel(logging.INFO)
if not logger.handlers:
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter(
        '\033[94m[RemediationEngine]\033[0m %(message)s'
    ))
    logger.addHandler(handler)


# ── Utilities ─────────────────────────────────────────────────────────────────

def finding_key(finding: dict) -> str:
    """Generate stable key for a finding."""
    key_parts = [
        finding.get('rule_id', ''),
        finding.get('file', ''),
        str(finding.get('line', 0)),
        finding.get('description', '')[:50],
    ]
    return hashlib.sha256('|'.join(key_parts).encode()).hexdigest()[:16]


def _run_command(
    cmd: List[str],
    cwd: Optional[str] = None,
    timeout: int = 60,
    env: Optional[Dict[str, str]] = None,
) -> Tuple[int, str, str]:
    """Run shell command and return (exit_code, stdout, stderr)."""
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**os.environ, **(env or {})},
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return -1, '', f'Command timeout after {timeout}s'
    except Exception as exc:
        return -1, '', str(exc)


# ── FixGenerator ──────────────────────────────────────────────────────────────

class FixGenerator:
    """Generates code patches using AI API."""

    def __init__(self, api_key: str, model: str = 'ai-model-latest'):
        self.api_key = api_key
        self.model = model
        self._session_cache: Dict[str, str] = {}

    def generate_fix(
        self,
        finding: dict,
        context_lines: int = 20,
    ) -> Optional[FixProposal]:
        """Generate a fix for the given finding."""
        start_time = time.time()

        try:
            # Read file context
            file_path = finding.get('file', '')
            if not os.path.isfile(file_path):
                logger.warning(f"File not found: {file_path}")
                return None

            with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
                lines = f.readlines()

            line_num = finding.get('line', 1)
            start_line = max(0, line_num - context_lines - 1)
            end_line = min(len(lines), line_num + context_lines)
            context = ''.join(lines[start_line:end_line])

            # Build prompt
            prompt = self._build_prompt(finding, context)

            # Call AI API
            response = self._call_ai_api(prompt)
            if not response:
                return None

            # Extract diff
            diff = self._extract_diff(response)
            if not diff:
                logger.warning(f"Could not extract diff from AI response for {finding_key(finding)}")
                return None

            # Validate diff syntax
            if not self._validate_diff_syntax(diff):
                logger.warning(f"Invalid diff syntax for {finding_key(finding)}")
                return None

            # Extract confidence and risk
            confidence = self._extract_confidence(response)
            risk = self._estimate_risk(finding, diff)

            elapsed_ms = int((time.time() - start_time) * 1000)

            return FixProposal(
                finding=finding,
                diff=diff,
                explanation=self._extract_explanation(response),
                confidence_score=confidence,
                affected_files=[file_path],
                estimated_risk=risk,
                generation_time_ms=elapsed_ms,
            )

        except Exception as exc:
            logger.error(f"Fix generation error for {finding_key(finding)}: {exc}")
            return None

    def _build_prompt(self, finding: dict, code_context: str) -> str:
        """Build AI prompt for fix generation."""
        return f"""You are a security remediation assistant. Generate a minimal, safe code patch to fix this security finding.

**Finding Details:**
- Rule: {finding.get('rule_id', 'Unknown')}
- Severity: {finding.get('severity', 'Unknown')}
- Description: {finding.get('description', 'No description')}
- File: {finding.get('file', 'unknown')}
- Line: {finding.get('line', 0)}

**Code Context:**
```
{code_context}
```

**Instructions:**
1. Provide ONLY the fix - no explanations before the code
2. Output a unified diff format patch
3. Keep changes minimal - only fix the security issue
4. Preserve all formatting and style
5. Do not introduce new vulnerabilities
6. After the diff, add a confidence score (0.0-1.0) on a line: "CONFIDENCE: X.X"
7. Add a brief explanation on a line starting with "EXPLANATION:"

**Output format:**
```diff
--- a/path/to/file
+++ b/path/to/file
@@ -line,count +line,count @@
 context
-removed line
+added line
 context
```
CONFIDENCE: 0.85
EXPLANATION: Brief explanation of the fix"""

    def _call_ai_api(self, prompt: str) -> Optional[str]:
        """Call AI API with retry logic."""
        import anthropic

        client = anthropic.Anthropic(api_key=self.api_key)

        for attempt in range(3):
            try:
                response = client.messages.create(
                    model=self.model,
                    max_tokens=4096,
                    temperature=0.3,
                    messages=[{
                        "role": "user",
                        "content": prompt,
                    }],
                )

                if response.content and len(response.content) > 0:
                    return response.content[0].text

                return None

            except Exception as exc:
                wait_time = 2 ** attempt
                logger.warning(f"AI API error (attempt {attempt + 1}/3): {exc}. Retrying in {wait_time}s...")
                if attempt < 2:
                    time.sleep(wait_time)

        return None

    def _extract_diff(self, response: str) -> Optional[str]:
        """Extract unified diff from AI response."""
        # Look for diff block
        diff_pattern = r'```diff\n(.*?)```'
        match = re.search(diff_pattern, response, re.DOTALL)
        if match:
            return match.group(1).strip()

        # Fallback: look for lines starting with --- or +++
        lines = response.split('\n')
        diff_start = -1
        for i, line in enumerate(lines):
            if line.startswith('---') or line.startswith('+++'):
                diff_start = i
                break

        if diff_start >= 0:
            # Extract until we hit a non-diff line
            diff_lines = []
            for line in lines[diff_start:]:
                if line.startswith(('---', '+++', '@@', ' ', '+', '-')):
                    diff_lines.append(line)
                elif line.strip() and not line.startswith('CONFIDENCE:') and not line.startswith('EXPLANATION:'):
                    break
            if diff_lines:
                return '\n'.join(diff_lines)

        return None

    def _validate_diff_syntax(self, diff: str) -> bool:
        """Validate that diff has proper unified diff format."""
        lines = diff.split('\n')
        if len(lines) < 3:
            return False

        # Must have --- and +++ headers
        has_minus = any(line.startswith('---') for line in lines[:5])
        has_plus = any(line.startswith('+++') for line in lines[:5])
        has_hunk = any(line.startswith('@@') for line in lines)

        return has_minus and has_plus and has_hunk

    def _extract_confidence(self, response: str) -> float:
        """Extract confidence score from response."""
        match = re.search(r'CONFIDENCE:\s*([0-9.]+)', response)
        if match:
            try:
                confidence = float(match.group(1))
                return max(0.0, min(1.0, confidence))
            except ValueError:
                pass
        return 0.7  # Default moderate confidence

    def _extract_explanation(self, response: str) -> str:
        """Extract explanation from response."""
        match = re.search(r'EXPLANATION:\s*(.+?)(?:\n|$)', response)
        if match:
            return match.group(1).strip()
        return "Automated security fix"

    def _estimate_risk(self, finding: dict, diff: str) -> RiskLevel:
        """Estimate risk level of applying this fix."""
        # Count lines changed
        lines_changed = sum(1 for line in diff.split('\n') if line.startswith(('+', '-')) and not line.startswith(('+++', '---')))

        # High risk if many lines changed
        if lines_changed > 20:
            return RiskLevel.HIGH

        # High risk for certain severities
        if finding.get('severity', '').upper() in ('CRITICAL', 'HIGH'):
            return RiskLevel.MEDIUM if lines_changed < 10 else RiskLevel.HIGH

        return RiskLevel.LOW if lines_changed < 5 else RiskLevel.MEDIUM


# ── SafetyValidator ───────────────────────────────────────────────────────────

class SafetyValidator:
    """Validates fixes before merging."""

    def __init__(self, test_orchestrator: TestOrchestrator):
        self.test_orchestrator = test_orchestrator
        self._validation_cache: Dict[str, ValidationResult] = {}

    def validate_pre_merge(
        self,
        diff: str,
        finding: dict,
        project_path: str,
    ) -> ValidationResult:
        """Validate that fix is safe to merge."""
        start_time = time.time()

        try:
            # Apply patch temporarily
            patched_files = self._apply_patch_temp(diff, project_path)
            if not patched_files:
                return ValidationResult(
                    passed=False,
                    tests_run=0,
                    tests_failed=0,
                    new_findings=[],
                    original_finding_resolved=False,
                    execution_time_ms=0,
                    error_message="Failed to apply patch",
                )

            # Run tests
            test_result = None
            test_suite = self.test_orchestrator.detect_test_suite(project_path)
            if test_suite:
                test_result = self.test_orchestrator.run_tests(test_suite)

            # Scan patched files
            new_findings = self._scan_patched_code(patched_files, project_path)

            # Check if original finding is resolved
            original_resolved = self._verify_finding_resolved(finding, new_findings)

            # Check complexity regression
            has_regression = False
            for file_path in patched_files:
                if self._check_complexity_regression(file_path, project_path):
                    has_regression = True
                    break

            elapsed_ms = int((time.time() - start_time) * 1000)

            passed = (
                (test_result is None or test_result.passed) and
                len(new_findings) == 0 and
                original_resolved and
                not has_regression
            )

            return ValidationResult(
                passed=passed,
                tests_run=test_result.tests_run if test_result else 0,
                tests_failed=test_result.tests_failed if test_result else 0,
                new_findings=new_findings,
                original_finding_resolved=original_resolved,
                execution_time_ms=elapsed_ms,
            )

        except Exception as exc:
            logger.error(f"Validation error: {exc}")
            return ValidationResult(
                passed=False,
                tests_run=0,
                tests_failed=0,
                new_findings=[],
                original_finding_resolved=False,
                execution_time_ms=int((time.time() - start_time) * 1000),
                error_message=str(exc),
            )

    def _apply_patch_temp(self, diff: str, project_path: str) -> List[str]:
        """Apply patch temporarily and return list of patched files."""
        try:
            # Write diff to temp file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.patch', delete=False) as f:
                f.write(diff)
                patch_file = f.name

            try:
                # Apply patch
                exit_code, _, stderr = _run_command(
                    ['git', 'apply', '--check', patch_file],
                    cwd=project_path,
                    timeout=10,
                )

                if exit_code != 0:
                    logger.warning(f"Patch check failed: {stderr}")
                    return []

                exit_code, _, _ = _run_command(
                    ['git', 'apply', patch_file],
                    cwd=project_path,
                    timeout=10,
                )

                if exit_code != 0:
                    return []

                # Extract affected files from diff
                affected = []
                for line in diff.split('\n'):
                    if line.startswith('+++'):
                        file_path = line.split(' ')[1]
                        if file_path.startswith('b/'):
                            file_path = file_path[2:]
                        affected.append(os.path.join(project_path, file_path))

                return affected

            finally:
                os.unlink(patch_file)

        except Exception as exc:
            logger.error(f"Failed to apply patch: {exc}")
            return []

    def _scan_patched_code(self, patched_files: List[str], project_path: str) -> List[dict]:
        """Scan patched files for new vulnerabilities."""
        from .analyzer import analyze_file
        from .rules_engine import RulesEngine
        from .taint_analyzer import TaintAnalyzer

        findings = []
        rules_engine = RulesEngine()
        taint_analyzer = TaintAnalyzer()

        for file_path in patched_files:
            if os.path.isfile(file_path):
                file_findings = analyze_file(
                    file_path,
                    rules_engine=rules_engine,
                    taint_analyzer=taint_analyzer,
                    all_findings_accumulator=findings,
                )

        return findings

    def _verify_finding_resolved(self, original_finding: dict, new_findings: List[dict]) -> bool:
        """Check if original finding no longer appears in new scan."""
        original_key = finding_key(original_finding)

        for new_finding in new_findings:
            if finding_key(new_finding) == original_key:
                return False

        return True

    def _check_complexity_regression(self, file_path: str, project_path: str) -> bool:
        """Check if fix increases code complexity significantly."""
        # This is a simplified check - in production you'd use tools like radon
        # For now, just check if file size increased dramatically
        try:
            # Get before/after from git
            exit_code, before, _ = _run_command(
                ['git', 'show', f'HEAD:{os.path.relpath(file_path, project_path)}'],
                cwd=project_path,
                timeout=5,
            )

            if exit_code != 0:
                return False

            with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
                after = f.read()

            # If file grew by more than 50%, flag it
            if len(after) > len(before) * 1.5:
                return True

            return False

        except Exception:
            return False


# ── TestOrchestrator ──────────────────────────────────────────────────────────

class TestOrchestrator:
    """Detects and runs test suites."""

    def detect_test_suite(self, project_path: str) -> Optional[TestSuite]:
        """Detect available test suite in project."""
        # Check for pytest
        if os.path.isfile(os.path.join(project_path, 'pytest.ini')) or \
           os.path.isfile(os.path.join(project_path, 'setup.py')) or \
           os.path.isdir(os.path.join(project_path, 'tests')):
            return TestSuite(
                runner='pytest',
                test_dir=os.path.join(project_path, 'tests'),
                command=['pytest', '-v', '--tb=short'],
                timeout=300,
            )

        # Check for jest
        if os.path.isfile(os.path.join(project_path, 'jest.config.js')) or \
           os.path.isfile(os.path.join(project_path, 'package.json')):
            return TestSuite(
                runner='jest',
                test_dir=project_path,
                command=['npm', 'test'],
                timeout=300,
            )

        # Check for go test
        if any(f.endswith('_test.go') for f in os.listdir(project_path) if os.path.isfile(os.path.join(project_path, f))):
            return TestSuite(
                runner='go',
                test_dir=project_path,
                command=['go', 'test', './...'],
                timeout=300,
            )

        return None

    def run_tests(self, test_suite: TestSuite, timeout: Optional[int] = None) -> TestResult:
        """Run test suite and return results."""
        start_time = time.time()
        timeout = timeout or test_suite.timeout

        exit_code, stdout, stderr = _run_command(
            test_suite.command,
            cwd=test_suite.test_dir,
            timeout=timeout,
        )

        elapsed_ms = int((time.time() - start_time) * 1000)

        # Parse output based on runner
        metrics = self._parse_test_output(stdout + stderr, test_suite.runner)

        return TestResult(
            passed=(exit_code == 0),
            tests_run=metrics.total,
            tests_failed=metrics.failed,
            execution_time_ms=elapsed_ms,
            stdout=stdout,
            stderr=stderr,
        )

    def _isolate_test_env(self, project_path: str) -> str:
        """Create isolated test environment."""
        # For now, just return the project path
        # In production, you'd create a Docker container or virtualenv
        return project_path

    def _parse_test_output(self, output: str, runner: str) -> TestMetrics:
        """Parse test runner output."""
        if runner == 'pytest':
            # Look for pytest summary line
            match = re.search(r'(\d+) passed.*?(?:(\d+) failed)?', output)
            if match:
                passed = int(match.group(1))
                failed = int(match.group(2) or 0)
                return TestMetrics(total=passed + failed, passed=passed, failed=failed)

        elif runner == 'jest':
            # Look for jest summary
            match = re.search(r'Tests:\s+(\d+) failed.*?(\d+) passed.*?(\d+) total', output)
            if match:
                failed = int(match.group(1))
                passed = int(match.group(2))
                total = int(match.group(3))
                return TestMetrics(total=total, passed=passed, failed=failed)

        elif runner == 'go':
            # Look for go test output
            if 'PASS' in output and 'FAIL' not in output:
                return TestMetrics(total=1, passed=1, failed=0)
            elif 'FAIL' in output:
                return TestMetrics(total=1, passed=0, failed=1)

        return TestMetrics(total=0, passed=0, failed=0)


# ── PRManager ─────────────────────────────────────────────────────────────────

class PRManager:
    """Manages PRs in GitHub/GitLab/Bitbucket."""

    def __init__(self, vcs_type: VCSType, token: str, repo: str, base_url: Optional[str] = None):
        self.vcs_type = vcs_type
        self.token = token
        self.repo = repo
        self.base_url = base_url or self._default_base_url()

    def _default_base_url(self) -> str:
        """Get default base URL for VCS type."""
        if self.vcs_type == VCSType.GITHUB:
            return 'https://api.github.com'
        elif self.vcs_type == VCSType.GITLAB:
            return 'https://gitlab.com/api/v4'
        elif self.vcs_type == VCSType.BITBUCKET:
            return 'https://api.bitbucket.org/2.0'
        return ''

    def create_fix_branch(self, base_branch: str, finding_id: str) -> str:
        """Create a new branch for the fix."""
        branch_name = f'auditlens/fix-{finding_id}-{int(time.time())}'

        exit_code, _, stderr = _run_command(
            ['git', 'checkout', '-b', branch_name, base_branch],
            timeout=10,
        )

        if exit_code != 0:
            raise RuntimeError(f"Failed to create branch: {stderr}")

        return branch_name

    def commit_fix(self, branch: str, diff: str, message: str) -> str:
        """Commit fix to branch and return commit SHA."""
        # Apply diff
        with tempfile.NamedTemporaryFile(mode='w', suffix='.patch', delete=False) as f:
            f.write(diff)
            patch_file = f.name

        try:
            exit_code, _, stderr = _run_command(
                ['git', 'apply', patch_file],
                timeout=10,
            )

            if exit_code != 0:
                raise RuntimeError(f"Failed to apply patch: {stderr}")

            # Stage changes
            exit_code, _, stderr = _run_command(
                ['git', 'add', '-u'],
                timeout=10,
            )

            if exit_code != 0:
                raise RuntimeError(f"Failed to stage changes: {stderr}")

            # Commit
            exit_code, _, stderr = _run_command(
                ['git', 'commit', '-m', message],
                timeout=10,
            )

            if exit_code != 0:
                raise RuntimeError(f"Failed to commit: {stderr}")

            # Get commit SHA
            exit_code, sha, _ = _run_command(
                ['git', 'rev-parse', 'HEAD'],
                timeout=5,
            )

            return sha.strip()

        finally:
            os.unlink(patch_file)

    def create_pull_request(
        self,
        branch: str,
        title: str,
        body: str,
        base_branch: str = 'main',
    ) -> PRMetadata:
        """Create pull request and return metadata."""
        # Push branch
        exit_code, _, stderr = _run_command(
            ['git', 'push', '-u', 'origin', branch],
            timeout=30,
        )

        if exit_code != 0:
            raise RuntimeError(f"Failed to push branch: {stderr}")

        # Create PR via API
        if self.vcs_type == VCSType.GITHUB:
            return self._create_github_pr(branch, title, body, base_branch)
        elif self.vcs_type == VCSType.GITLAB:
            return self._create_gitlab_mr(branch, title, body, base_branch)
        else:
            raise NotImplementedError(f"VCS type {self.vcs_type} not yet implemented")

    def _create_github_pr(self, branch: str, title: str, body: str, base: str) -> PRMetadata:
        """Create GitHub Pull Request."""
        url = f"{self.base_url}/repos/{self.repo}/pulls"
        headers = {
            'Authorization': f'token {self.token}',
            'Accept': 'application/vnd.github.v3+json',
        }
        payload = {
            'title': title,
            'body': body,
            'head': branch,
            'base': base,
        }

        response = requests.post(url, json=payload, headers=headers, timeout=30)
        response.raise_for_status()

        data = response.json()

        return PRMetadata(
            pr_id=str(data['number']),
            pr_url=data['html_url'],
            branch=branch,
            commit_sha=data['head']['sha'],
            created_at=datetime.now(timezone.utc),
            status=PRStatus.OPEN,
            finding_id=branch.split('-')[1] if '-' in branch else '',
        )

    def _create_gitlab_mr(self, branch: str, title: str, body: str, base: str) -> PRMetadata:
        """Create GitLab Merge Request."""
        # Get project ID
        project_id = self.repo.replace('/', '%2F')
        url = f"{self.base_url}/projects/{project_id}/merge_requests"
        headers = {
            'PRIVATE-TOKEN': self.token,
            'Content-Type': 'application/json',
        }
        payload = {
            'source_branch': branch,
            'target_branch': base,
            'title': title,
            'description': body,
        }

        response = requests.post(url, json=payload, headers=headers, timeout=30)
        response.raise_for_status()

        data = response.json()

        return PRMetadata(
            pr_id=str(data['iid']),
            pr_url=data['web_url'],
            branch=branch,
            commit_sha=data['sha'],
            created_at=datetime.now(timezone.utc),
            status=PRStatus.OPEN,
            finding_id=branch.split('-')[1] if '-' in branch else '',
        )

    def merge_pr(self, pr_id: str) -> bool:
        """Merge the pull request."""
        if self.vcs_type == VCSType.GITHUB:
            url = f"{self.base_url}/repos/{self.repo}/pulls/{pr_id}/merge"
            headers = {
                'Authorization': f'token {self.token}',
                'Accept': 'application/vnd.github.v3+json',
            }
            response = requests.put(url, headers=headers, timeout=30)
            return response.status_code == 200

        return False

    def close_pr(self, pr_id: str, reason: str) -> bool:
        """Close the pull request without merging."""
        if self.vcs_type == VCSType.GITHUB:
            url = f"{self.base_url}/repos/{self.repo}/pulls/{pr_id}"
            headers = {
                'Authorization': f'token {self.token}',
                'Accept': 'application/vnd.github.v3+json',
            }
            payload = {'state': 'closed'}
            response = requests.patch(url, json=payload, headers=headers, timeout=30)
            return response.status_code == 200

        return False


# ── RollbackManager ───────────────────────────────────────────────────────────

class RollbackManager:
    """Manages rollback snapshots."""

    def __init__(self, snapshot_dir: Optional[str] = None):
        self.snapshot_dir = snapshot_dir or os.path.join(
            os.path.expanduser('~'),
            '.auditlens',
            'snapshots',
        )
        os.makedirs(self.snapshot_dir, exist_ok=True)

    def create_snapshot(self, finding: dict, file_state: Dict[str, str]) -> SnapshotID:
        """Create snapshot of current state."""
        snapshot_id = SnapshotID(
            id=hashlib.sha256(f"{finding_key(finding)}{time.time()}".encode()).hexdigest()[:16],
            timestamp=datetime.now(timezone.utc),
        )

        # Save using git stash
        exit_code, stdout, _ = _run_command(
            ['git', 'stash', 'create'],
            timeout=10,
        )

        if exit_code == 0 and stdout.strip():
            stash_ref = stdout.strip()

            # Save metadata
            metadata = {
                'snapshot_id': snapshot_id.id,
                'timestamp': snapshot_id.timestamp.isoformat(),
                'finding_key': finding_key(finding),
                'git_stash_ref': stash_ref,
                'file_state': file_state,
            }

            snapshot_file = os.path.join(self.snapshot_dir, f"{snapshot_id.id}.json")
            with open(snapshot_file, 'w', encoding='utf-8') as f:
                json.dump(metadata, f, indent=2)

        return snapshot_id

    def rollback_to_snapshot(self, snapshot_id: SnapshotID) -> RollbackResult:
        """Rollback to snapshot."""
        snapshot_file = os.path.join(self.snapshot_dir, f"{snapshot_id.id}.json")

        if not os.path.isfile(snapshot_file):
            return RollbackResult(
                success=False,
                reverted_files=[],
                error_message=f"Snapshot not found: {snapshot_id.id}",
            )

        try:
            with open(snapshot_file, 'r', encoding='utf-8') as f:
                metadata = json.load(f)

            stash_ref = metadata.get('git_stash_ref')
            if not stash_ref:
                return RollbackResult(
                    success=False,
                    reverted_files=[],
                    error_message="No stash ref in snapshot",
                )

            # Apply stash
            exit_code, _, stderr = _run_command(
                ['git', 'stash', 'apply', stash_ref],
                timeout=30,
            )

            if exit_code != 0:
                return RollbackResult(
                    success=False,
                    reverted_files=[],
                    error_message=f"Failed to apply stash: {stderr}",
                )

            # Verify integrity
            file_state = metadata.get('file_state', {})
            if not self._verify_rollback_integrity(file_state):
                return RollbackResult(
                    success=False,
                    reverted_files=[],
                    error_message="Integrity check failed after rollback",
                )

            return RollbackResult(
                success=True,
                reverted_files=list(file_state.keys()),
            )

        except Exception as exc:
            return RollbackResult(
                success=False,
                reverted_files=[],
                error_message=str(exc),
            )

    def _verify_rollback_integrity(self, expected_state: Dict[str, str]) -> bool:
        """Verify that files match expected state after rollback."""
        for file_path, expected_hash in expected_state.items():
            if not os.path.isfile(file_path):
                return False

            with open(file_path, 'rb') as f:
                actual_hash = hashlib.sha256(f.read()).hexdigest()

            if actual_hash != expected_hash:
                return False

        return True

    def cleanup_snapshots(self, older_than_days: int = 30) -> int:
        """Clean up old snapshots. Returns number of snapshots deleted."""
        cutoff = datetime.now(timezone.utc).timestamp() - (older_than_days * 86400)
        deleted = 0

        for filename in os.listdir(self.snapshot_dir):
            if not filename.endswith('.json'):
                continue

            file_path = os.path.join(self.snapshot_dir, filename)

            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    metadata = json.load(f)

                timestamp = datetime.fromisoformat(metadata['timestamp']).timestamp()

                if timestamp < cutoff:
                    os.unlink(file_path)
                    deleted += 1

            except Exception:
                pass

        return deleted


# ── RemediationTracker ────────────────────────────────────────────────────────

class RemediationTracker:
    """Tracks remediation history in SQLite."""

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = db_path or os.path.join(
            os.path.expanduser('~'),
            '.auditlens',
            'remediation.db',
        )
        self._init_db()

    def _init_db(self):
        """Initialize database schema."""
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)

        conn = sqlite3.connect(self.db_path)
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS remediations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                finding_key TEXT NOT NULL,
                pr_metadata TEXT NOT NULL,
                applied_at TEXT NOT NULL,
                status TEXT NOT NULL,
                validation_result TEXT,
                rollback_reason TEXT
            );

            CREATE INDEX IF NOT EXISTS idx_finding_key ON remediations(finding_key);
            CREATE INDEX IF NOT EXISTS idx_status ON remediations(status);
            CREATE INDEX IF NOT EXISTS idx_applied_at ON remediations(applied_at);
        """)
        conn.commit()
        conn.close()

    def record_fix(
        self,
        finding: dict,
        pr_metadata: Optional[PRMetadata],
        status: FixStatus,
        validation_result: Optional[ValidationResult] = None,
    ) -> int:
        """Record a fix attempt. Returns record ID."""
        conn = sqlite3.connect(self.db_path)

        try:
            cursor = conn.execute(
                """
                INSERT INTO remediations
                  (finding_key, pr_metadata, applied_at, status, validation_result)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    finding_key(finding),
                    json.dumps(asdict(pr_metadata) if pr_metadata else {}, default=str),
                    datetime.now(timezone.utc).isoformat(),
                    status.value,
                    json.dumps(asdict(validation_result) if validation_result else {}, default=str),
                ),
            )
            conn.commit()
            return cursor.lastrowid
        finally:
            conn.close()

    def get_fix_history(self, finding_key_str: str) -> List[FixRecord]:
        """Get fix history for a finding."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row

        try:
            rows = conn.execute(
                """
                SELECT id, finding_key, pr_metadata, applied_at, status,
                       validation_result, rollback_reason
                FROM remediations
                WHERE finding_key = ?
                ORDER BY applied_at DESC
                """,
                (finding_key_str,),
            ).fetchall()

            records = []
            for row in rows:
                records.append(FixRecord(
                    id=row['id'],
                    finding_key=row['finding_key'],
                    pr_metadata=row['pr_metadata'],
                    applied_at=datetime.fromisoformat(row['applied_at']),
                    status=FixStatus(row['status']),
                    validation_result=row['validation_result'],
                    rollback_reason=row['rollback_reason'],
                ))

            return records
        finally:
            conn.close()

    def mark_rollback(self, pr_id: str, reason: str) -> bool:
        """Mark a fix as rolled back."""
        conn = sqlite3.connect(self.db_path)

        try:
            conn.execute(
                """
                UPDATE remediations
                SET status = ?, rollback_reason = ?
                WHERE json_extract(pr_metadata, '$.pr_id') = ?
                """,
                (FixStatus.ROLLED_BACK.value, reason, pr_id),
            )
            conn.commit()
            return True
        except Exception as exc:
            logger.error(f"Failed to mark rollback: {exc}")
            return False
        finally:
            conn.close()

    def get_success_rate(self, time_window_days: int = 30) -> float:
        """Get success rate over time window."""
        conn = sqlite3.connect(self.db_path)

        try:
            cutoff = (datetime.now(timezone.utc).timestamp() - (time_window_days * 86400))
            cutoff_iso = datetime.fromtimestamp(cutoff, tz=timezone.utc).isoformat()

            cursor = conn.execute(
                """
                SELECT
                  SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END) as successful,
                  COUNT(*) as total
                FROM remediations
                WHERE applied_at >= ?
                """,
                (cutoff_iso,),
            )

            row = cursor.fetchone()
            if row and row[1] > 0:
                return row[0] / row[1]

            return 0.0
        finally:
            conn.close()


# ── RemediationEngine ─────────────────────────────────────────────────────────

class RemediationEngine:
    """Main orchestrator for automated remediation."""

    def __init__(self, config: RemediationConfig, api_key: Optional[str] = None):
        self.config = config
        self.api_key = api_key or os.environ.get('ANTHROPIC_API_KEY', '')

        # Initialize components
        self.fix_generator = FixGenerator(self.api_key)
        self.test_orchestrator = TestOrchestrator()
        self.safety_validator = SafetyValidator(self.test_orchestrator)
        self.pr_manager = PRManager(
            config.vcs_type,
            config.vcs_token or os.environ.get('GITHUB_TOKEN', ''),
            config.repo,
            config.vcs_url,
        )
        self.rollback_manager = RollbackManager()
        self.tracker = RemediationTracker()

        # File-level locks for parallel processing
        self._file_locks: Dict[str, threading.Lock] = {}
        self._lock_lock = threading.Lock()

    def remediate(
        self,
        findings: List[dict],
        mode: RemediationMode = RemediationMode.SAFE,
    ) -> RemediationReport:
        """Run remediation on findings."""
        start_time = time.time()

        # Filter findings by mode
        filtered = self._filter_by_mode(findings, mode)

        # Limit batch size
        if len(filtered) > self.config.max_fixes_per_run:
            logger.warning(
                f"Limiting fixes from {len(filtered)} to {self.config.max_fixes_per_run}"
            )
            filtered = filtered[:self.config.max_fixes_per_run]

        logger.info(f"Starting remediation for {len(filtered)} findings (mode: {mode.value})")

        # Group findings by file for parallel processing
        by_file: Dict[str, List[dict]] = {}
        for finding in filtered:
            file_path = finding.get('file', '')
            if file_path not in by_file:
                by_file[file_path] = []
            by_file[file_path].append(finding)

        # Process in parallel
        prs_created = []
        successful = 0
        failed = 0
        rollbacks = 0

        with ThreadPoolExecutor(max_workers=3) as executor:
            futures = {}

            for file_path, file_findings in by_file.items():
                for finding in file_findings:
                    future = executor.submit(self._remediate_single, finding)
                    futures[future] = finding

            for future in as_completed(futures):
                finding = futures[future]
                try:
                    result = future.result()
                    if result['success']:
                        successful += 1
                        if result['pr_metadata']:
                            prs_created.append(result['pr_metadata'])
                    else:
                        failed += 1
                        if result.get('rolled_back'):
                            rollbacks += 1
                except Exception as exc:
                    logger.error(f"Remediation failed for {finding_key(finding)}: {exc}")
                    failed += 1

        elapsed = time.time() - start_time

        return RemediationReport(
            total_findings=len(findings),
            fixes_attempted=len(filtered),
            fixes_successful=successful,
            fixes_failed=failed,
            prs_created=prs_created,
            rollbacks=rollbacks,
            execution_time_seconds=elapsed,
            success_rate=successful / len(filtered) if filtered else 0.0,
        )

    def _filter_by_mode(self, findings: List[dict], mode: RemediationMode) -> List[dict]:
        """Filter findings based on remediation mode."""
        if mode == RemediationMode.SAFE:
            return [f for f in findings if f.get('severity', '').upper() in ('HIGH', 'CRITICAL')]
        elif mode == RemediationMode.MODERATE:
            return [f for f in findings if f.get('severity', '').upper() in ('MEDIUM', 'HIGH', 'CRITICAL')]
        else:  # AGGRESSIVE
            return findings

    def _remediate_single(self, finding: dict) -> dict:
        """Remediate a single finding."""
        fkey = finding_key(finding)
        logger.info(f"Processing {fkey}: {finding.get('rule_id', '')} in {finding.get('file', '')}")

        try:
            # Generate fix
            proposal = self._generate_fix(finding)
            if not proposal:
                self.tracker.record_fix(finding, None, FixStatus.FAILED)
                return {'success': False, 'error': 'Failed to generate fix'}

            # Validate fix
            project_path = os.path.dirname(finding.get('file', '.')) or '.'
            validation = self._validate_fix(proposal, project_path)

            if not validation.passed:
                logger.warning(f"Validation failed for {fkey}: {validation.error_message}")
                self.tracker.record_fix(finding, None, FixStatus.FAILED, validation)
                return {'success': False, 'error': 'Validation failed', 'validation': validation}

            # Create PR
            pr_metadata = self._create_pr(proposal)

            if not pr_metadata:
                self.tracker.record_fix(finding, None, FixStatus.FAILED, validation)
                return {'success': False, 'error': 'Failed to create PR'}

            # Record success
            self.tracker.record_fix(finding, pr_metadata, FixStatus.SUCCESS, validation)

            logger.info(f"✓ Fix applied for {fkey}: {pr_metadata.pr_url}")

            return {
                'success': True,
                'pr_metadata': pr_metadata,
                'validation': validation,
            }

        except Exception as exc:
            logger.error(f"Remediation error for {fkey}: {exc}")
            self.tracker.record_fix(finding, None, FixStatus.FAILED)
            return {'success': False, 'error': str(exc)}

    def _generate_fix(self, finding: dict) -> Optional[FixProposal]:
        """Generate fix for finding."""
        return self.fix_generator.generate_fix(finding)

    def _validate_fix(self, proposal: FixProposal, project_path: str) -> ValidationResult:
        """Validate fix proposal."""
        return self.safety_validator.validate_pre_merge(
            proposal.diff,
            proposal.finding,
            project_path,
        )

    def _create_pr(self, proposal: FixProposal) -> Optional[PRMetadata]:
        """Create pull request for fix."""
        try:
            fkey = finding_key(proposal.finding)
            branch = self.pr_manager.create_fix_branch(self.config.base_branch, fkey)

            commit_msg = self._build_commit_message(proposal)
            self.pr_manager.commit_fix(branch, proposal.diff, commit_msg)

            title, body = self._build_pr_content(proposal)
            pr_metadata = self.pr_manager.create_pull_request(
                branch,
                title,
                body,
                self.config.base_branch,
            )

            return pr_metadata

        except Exception as exc:
            logger.error(f"Failed to create PR: {exc}")
            return None

    def _build_commit_message(self, proposal: FixProposal) -> str:
        """Build commit message for fix."""
        finding = proposal.finding
        return f"fix: {finding.get('rule_id', 'security')} in {Path(finding.get('file', '')).name}\n\n{proposal.explanation}"

    def _build_pr_content(self, proposal: FixProposal) -> Tuple[str, str]:
        """Build PR title and body."""
        finding = proposal.finding

        title = f"[AuditLens] Fix {finding.get('rule_id', 'security issue')} in {Path(finding.get('file', '')).name}"

        body = f"""## Automated Security Fix

**Finding:** {finding.get('name', 'Security Issue')}
**Rule ID:** {finding.get('rule_id', 'N/A')}
**Severity:** {finding.get('severity', 'Unknown')}
**File:** `{finding.get('file', 'unknown')}`:{finding.get('line', 0)}

### Description
{finding.get('description', 'No description available')}

### Fix Applied
{proposal.explanation}

### Confidence
{proposal.confidence_score:.1%}

### Risk Level
{proposal.estimated_risk.value.upper()}

---
🤖 This PR was automatically generated by [AuditLens](https://github.com/MasterCapehart/auditlens) using AI.
"""

        return title, body

    def _rollback_on_failure(self, pr_metadata: PRMetadata, error: Exception):
        """Rollback a failed fix."""
        logger.warning(f"Rolling back PR {pr_metadata.pr_id} due to: {error}")

        try:
            self.pr_manager.close_pr(pr_metadata.pr_id, str(error))
            self.tracker.mark_rollback(pr_metadata.pr_id, str(error))
        except Exception as exc:
            logger.error(f"Rollback failed: {exc}")


# ── Public APIs ───────────────────────────────────────────────────────────────

def generate_fix_pr(
    finding: dict,
    target_branch: str = 'main',
    auto_merge: bool = False,
    api_key: Optional[str] = None,
    vcs_token: Optional[str] = None,
) -> PRResult:
    """Generate a Pull Request with automated fix for a finding."""
    # Extract repo from finding file path (assumes git repo)
    file_path = finding.get('file', '')
    if not file_path:
        return PRResult(None, False, "No file path in finding")

    # Try to get repo info from git
    try:
        exit_code, remote_url, _ = _run_command(
            ['git', 'config', '--get', 'remote.origin.url'],
            cwd=os.path.dirname(file_path) or '.',
            timeout=5,
        )

        if exit_code != 0:
            return PRResult(None, False, "Not in a git repository")

        # Parse repo from URL
        repo_match = re.search(r'[:/]([^/]+/[^/]+?)(?:\.git)?$', remote_url.strip())
        if not repo_match:
            return PRResult(None, False, "Could not parse repo from git remote")

        repo = repo_match.group(1)

    except Exception as exc:
        return PRResult(None, False, f"Failed to get git repo: {exc}")

    config = RemediationConfig(
        vcs_type=VCSType.GITHUB,  # Default to GitHub
        repo=repo,
        base_branch=target_branch,
        auto_merge=auto_merge,
        vcs_token=vcs_token,
    )

    engine = RemediationEngine(config, api_key)
    result = engine._remediate_single(finding)

    if result['success']:
        return PRResult(result['pr_metadata'], True)
    else:
        return PRResult(None, False, result.get('error', 'Unknown error'))


def apply_fix_batch(
    findings: List[dict],
    strategy: FixStrategy = FixStrategy.SAFE,
    api_key: Optional[str] = None,
    vcs_token: Optional[str] = None,
) -> BatchResult:
    """Apply fixes to multiple findings in batch."""
    if not findings:
        return BatchResult(0, 0, 0, [], [])

    # Use first finding to get repo info
    file_path = findings[0].get('file', '')
    try:
        exit_code, remote_url, _ = _run_command(
            ['git', 'config', '--get', 'remote.origin.url'],
            cwd=os.path.dirname(file_path) or '.',
            timeout=5,
        )

        repo_match = re.search(r'[:/]([^/]+/[^/]+?)(?:\.git)?$', remote_url.strip())
        repo = repo_match.group(1) if repo_match else 'unknown/repo'

    except Exception:
        repo = 'unknown/repo'

    config = RemediationConfig(
        vcs_type=VCSType.GITHUB,
        repo=repo,
        vcs_token=vcs_token,
    )

    engine = RemediationEngine(config, api_key)
    report = engine.remediate(findings, RemediationMode(strategy.value))

    pr_urls = [pr.pr_url for pr in report.prs_created]
    errors = []

    return BatchResult(
        total_attempted=report.fixes_attempted,
        successful=report.fixes_successful,
        failed=report.fixes_failed,
        pr_urls=pr_urls,
        errors=errors,
    )


def validate_fix(original_finding: dict, patched_code: str) -> ValidationResult:
    """Validate that a fix doesn't introduce new problems."""
    # Create temp file with patched code
    file_path = original_finding.get('file', '')

    with tempfile.NamedTemporaryFile(mode='w', suffix=Path(file_path).suffix, delete=False) as f:
        f.write(patched_code)
        temp_file = f.name

    try:
        # Scan the patched file
        from .analyzer import analyze_file
        from .rules_engine import RulesEngine
        from .taint_analyzer import TaintAnalyzer

        findings = []
        analyze_file(
            temp_file,
            rules_engine=RulesEngine(),
            taint_analyzer=TaintAnalyzer(),
            all_findings_accumulator=findings,
        )

        # Check if original finding is gone
        original_key = finding_key(original_finding)
        original_resolved = not any(finding_key(f) == original_key for f in findings)

        return ValidationResult(
            passed=(len(findings) == 0 and original_resolved),
            tests_run=0,
            tests_failed=0,
            new_findings=findings,
            original_finding_resolved=original_resolved,
            execution_time_ms=0,
        )

    finally:
        os.unlink(temp_file)


def rollback_fix(pr_url: str, reason: str) -> RollbackResult:
    """Revert a fix that was applied."""
    # Extract PR ID from URL
    pr_match = re.search(r'/pull/(\d+)', pr_url)
    if not pr_match:
        return RollbackResult(False, [], "Invalid PR URL")

    pr_id = pr_match.group(1)

    # This is a simplified implementation
    # In production, you'd need to get repo info and close the PR
    tracker = RemediationTracker()
    success = tracker.mark_rollback(pr_id, reason)

    return RollbackResult(
        success=success,
        reverted_files=[],
        error_message=None if success else "Failed to mark rollback",
    )


def schedule_remediation(
    findings: List[dict],
    schedule: str,
    approval_required: bool = True,
) -> ScheduleResult:
    """Schedule automated remediation for recurring findings."""
    # This would integrate with a cron/scheduler system
    # For now, just return a placeholder
    schedule_id = hashlib.sha256(f"{schedule}{time.time()}".encode()).hexdigest()[:16]

    return ScheduleResult(
        schedule_id=schedule_id,
        cron_expression=schedule,
        findings_count=len(findings),
        approval_required=approval_required,
        created_at=datetime.now(timezone.utc),
    )
